export const siteConfig = {
  name: "Pritom Chaki",
  title: "Pritom Chaki - Flutter Developer & App Developer",
  description:
    "Pritom Chaki is a Flutter Developer, Laravel Developer, and App Developer from Bangladesh. Building elegant, performant mobile and web applications.",
  url: "https://www.pritom.me",
  ogImage: "/og-image.png",
  links: {
    github: "https://github.com/Pritom-Chaki",
    linkedin: "https://www.linkedin.com/in/pritom-chaki-cse",
    twitter: "https://www.twitter.com/PritomChaki",
    facebook: "https://www.facebook.com/pritom.chaki.77",
    instagram: "https://www.instagram.com/pritom_chaki",
    email: "pritom.chaki@gmail.com",
  },
  author: {
    name: "Pritom Chaki",
    role: "Flutter Developer | Laravel Developer | App Developer",
    location: "Bangladesh",
    bio: "I love coding and app development with a passion, and solving challenging problems by working with others to hit deadlines. I specialize in Flutter, Laravel, and mobile app development.",
    avatar: "/avatar.jpg",
  },
  skills: [
    { name: "Flutter", category: "Mobile" },
    { name: "Dart", category: "Language" },
    { name: "Android", category: "Mobile" },
    { name: "iOS", category: "Mobile" },
    { name: "Laravel", category: "Backend" },
    { name: "PHP", category: "Language" },
    { name: "Kotlin", category: "Language" },
    { name: "Java", category: "Language" },
    { name: "JavaScript", category: "Language" },
    { name: "TypeScript", category: "Language" },
    { name: "React", category: "Web" },
    { name: "Next.js", category: "Web" },
    { name: "Node.js", category: "Backend" },
    { name: "Firebase", category: "Backend" },
    { name: "REST API", category: "Backend" },
    { name: "MySQL", category: "Database" },
    { name: "Git", category: "Tools" },
    { name: "CI/CD", category: "Tools" },
    { name: "Figma", category: "Design" },
    { name: "Material Design", category: "Design" },
  ],
  navLinks: [
    { name: "Home", href: "/" },
    { name: "About", href: "/about" },
    { name: "Projects", href: "/projects" },
    { name: "Flutter Packages", href: "/flutter-packages" },
    { name: "Blog", href: "/blog" },
    { name: "Contact", href: "/contact" },
  ],
};

export const GA_MEASUREMENT_ID = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID || "";
